In [1]:
using LinearAlgebra

In [2]:
# Republicanos e monarquistas

function calcula(k)
    r0, m0 = 50, 50
    r, m = 0, 0
    
    # println("Ano 0: ", (r0, m0))
    for i=1:k
        r = 0.7*r0 + 0.2*m0
        m = 0.3*r0 + 0.8*m0
        r0, m0 = r, m
        # println("Ano ", i, ": ", (r, m))
    end
    
    return r, m
end

calcula (generic function with 1 method)

In [3]:
calcula(10)

(40.009765625, 59.990234375)

In [4]:
calcula(52)

(40.0, 60.0)

In [5]:
# Bactérias

function sistema_pop(t, p0)
    p = zeros(4)
    T = [0 0.5 0.2; 0.8 0 0; 0 0.5 0]
    
    println("Mês 0: ", p0)
    for i=1:t-1
        p = T*p0
        p0 = p
        println("Mês ", i, ": ", p)
    end
    
    p = T*p0
    println("Mês ", t, ": ", p)
    return p
end

sistema_pop (generic function with 1 method)

In [6]:
p0 = [250; 0; 0]
sistema_pop(5, p0)

Mês 0: [250, 0, 0]
Mês 1: [0.0, 200.0, 0.0]
Mês 2: [100.0, 0.0, 100.0]
Mês 3: [20.0, 80.0, 0.0]
Mês 4: [40.0, 16.0, 40.0]
Mês 5: [16.0, 32.0, 8.0]


3-element Vector{Float64}:
 16.0
 32.0
  8.0

In [7]:
sistema_pop(1000, p0)

Mês 0: [250, 0, 0]
Mês 1: [0.0, 200.0, 0.0]
Mês 2: [100.0, 0.0, 100.0]
Mês 3: [20.0, 80.0, 0.0]
Mês 4: [40.0, 16.0, 40.0]
Mês 5: [16.0, 32.0, 8.0]
Mês 6: [17.6, 12.8, 16.0]
Mês 7: [9.600000000000001, 14.080000000000002, 6.4]
Mês 8: [8.32, 7.6800000000000015, 7.040000000000001]
Mês 9: [5.248000000000001, 6.656000000000001, 3.8400000000000007]
Mês 10: [4.096, 4.198400000000001, 3.3280000000000003]
Mês 11: [2.7648000000000006, 3.2768, 2.0992000000000006]
Mês 12: [2.05824, 2.2118400000000005, 1.6384]
Mês 13: [1.4336000000000002, 1.646592, 1.1059200000000002]
Mês 14: [1.04448, 1.1468800000000001, 0.823296]
Mês 15: [0.7380992000000001, 0.8355840000000001, 0.5734400000000001]
Mês 16: [0.5324800000000001, 0.5904793600000001, 0.41779200000000005]
Mês 17: [0.3787980800000001, 0.4259840000000001, 0.29523968000000006]
Mês 18: [0.27203993600000004, 0.3030384640000001, 0.21299200000000004]
Mês 19: [0.19411763200000007, 0.21763194880000003, 0.15151923200000006]
Mês 20: [0.13911982080000002, 0.1552941

Mês 121: [2.841972370502353e-16, 3.17797182775667e-16, 2.2210598005017417e-16]
Mês 122: [2.0331978739786836e-16, 2.273577896401883e-16, 1.588985913878335e-16]
Mês 123: [1.4545861309766085e-16, 1.626558299182947e-16, 1.1367889482009414e-16]
Mês 124: [1.0406369392316618e-16, 1.163668904781287e-16, 8.132791495914735e-17]
Mês 125: [7.444902823089381e-17, 8.325095513853295e-17, 5.818344523906435e-17]
Mês 126: [5.3262166617079345e-17, 5.955922258471505e-17, 4.162547756926647e-17]
Mês 127: [3.810470680621082e-17, 4.260973329366348e-17, 2.9779611292357525e-17]
Mês 128: [2.7260788905303245e-17, 3.048376544496866e-17, 2.130486664683174e-17]
Mês 129: [1.9502856051850676e-17, 2.1808631124242596e-17, 1.524188272248433e-17]
Mês 130: [1.3952692106618165e-17, 1.560228484148054e-17, 1.0904315562121298e-17]
Mês 131: [9.98200553316453e-18, 1.1162153685294533e-17, 7.80114242074027e-18]
Mês 132: [7.141305326795321e-18, 7.985604426531625e-18, 5.5810768426472664e-18]
Mês 133: [5.109017581795266e-18, 5.713044

Mês 226: [1.5219429641247006e-31, 1.7018785663232308e-31, 1.1894296972620895e-31]
Mês 227: [1.0888252226140333e-31, 1.2175543712997605e-31, 8.509392831616154e-32]
Mês 228: [7.789650422822033e-32, 8.710601780912267e-32, 6.087771856498802e-32]
Mês 229: [5.572855261755894e-32, 6.231720338257627e-32, 4.3553008904561334e-32]
Mês 230: [3.98692034722004e-32, 4.458284209404715e-32, 3.1158601691288134e-32]
Mês 231: [2.85231413852812e-32, 3.1895362777760323e-32, 2.2291421047023574e-32]
Mês 232: [2.0405965598284876e-32, 2.2818513108224962e-32, 1.5947681388880162e-32]
Mês 233: [1.4598792831888514e-32, 1.63247724786279e-32, 1.1409256554112481e-32]
Mês 234: [1.0444237550136447e-32, 1.1679034265510811e-32, 8.16238623931395e-33]
Mês 235: [7.471994380618196e-33, 8.355390040109159e-33, 5.839517132755406e-33]
Mês 236: [5.3455984466056605e-33, 5.977595504494557e-33, 4.177695020054579e-33]
Mês 237: [3.824336756258194e-33, 4.276478757284529e-33, 2.9887977522472786e-33]
Mês 238: [2.7359989290917202e-33, 3.05

Mês 333: [4.1715407852150953e-47, 4.664731871199778e-47, 3.260144834749739e-47]
Mês 334: [2.9843949025498366e-47, 3.3372326281720764e-47, 2.332365935599889e-47]
Mês 335: [2.135089501206016e-47, 2.3875159220398694e-47, 1.6686163140860382e-47]
Mês 336: [1.5274812238371423e-47, 1.7080716009648128e-47, 1.1937579610199347e-47]
Mês 337: [1.0927873926863933e-47, 1.221984979069714e-47, 8.540358004824064e-48]
Mês 338: [7.817996496313382e-48, 8.742299141491147e-48, 6.10992489534857e-48]
Mês 339: [5.593134549815288e-48, 6.254397197050706e-48, 4.3711495707455737e-48]
Mês 340: [4.001428512674468e-48, 4.4745076398522305e-48, 3.127198598525353e-48]
Mês 341: [2.862693539631186e-48, 3.2011428101395745e-48, 2.2372538199261153e-48]
Mês 342: [2.0480221690550103e-48, 2.290154831704949e-48, 1.6005714050697872e-48]
Mês 343: [1.4651916968664318e-48, 1.6384177352440084e-48, 1.1450774158524744e-48]
Mês 344: [1.048224350792499e-48, 1.1721533574931455e-48, 8.192088676220042e-49]
Mês 345: [7.499184522709737e-49, 8

Mês 445: [2.1428589646128042e-63, 2.3962039501431106e-63, 1.6746883093747314e-63]
Mês 446: [1.5330396369465015e-63, 1.7142871716902435e-63, 1.1981019750715553e-63]
Mês 447: [1.0967639808594328e-63, 1.2264317095572014e-63, 8.571435858451217e-64]
Mês 448: [7.846445719476251e-64, 8.774111846875463e-64, 6.132158547786007e-64]
Mês 449: [5.613487632994933e-64, 6.277156575581001e-64, 4.387055923437732e-64]
Mês 450: [4.015989472478047e-64, 4.490790106395947e-64, 3.1385782877905005e-64]
Mês 451: [2.8731107107560737e-64, 3.2127915779824375e-64, 2.2453950531979734e-64]
Mês 452: [2.0554747996308135e-64, 2.298488568604859e-64, 1.6063957889912187e-64]
Mês 453: [1.4705234421006733e-64, 1.644379839704651e-64, 1.1492442843024295e-64]
Mês 454: [1.0520387767128113e-64, 1.1764187536805387e-64, 8.221899198523255e-65]
Mês 455: [7.526473608107345e-65, 8.416310213702491e-65, 5.8820937684026935e-65]
Mês 456: [5.384573860531784e-65, 6.021178886485877e-65, 4.208155106851246e-65]
Mês 457: [3.8522204646131875e-65,

Mês 556: [1.5386182767897883e-79, 1.720525360506988e-79, 1.2024617967313313e-79]
Mês 557: [1.1007550395997603e-79, 1.2308946214318307e-79, 8.60262680253494e-80]
Mês 558: [7.874998467666141e-80, 8.806040316798082e-80, 6.154473107159153e-80]
Mês 559: [5.633914779830872e-80, 6.299998774132914e-80, 4.403020158399041e-80]
Mês 560: [4.030603418746265e-80, 4.507131823864698e-80, 3.149999387066457e-80]
Mês 561: [2.8835657893456403e-80, 3.2244827349970123e-80, 2.253565911932349e-80]
Mês 562: [2.062954549884976e-80, 2.3068526314765124e-80, 1.6122413674985061e-80]
Mês 563: [1.4758745892379573e-80, 1.6503636399079808e-80, 1.1534263157382562e-80]
Mês 564: [1.0558670831016417e-80, 1.180699671390366e-80, 8.251818199539904e-81]
Mês 565: [7.553861996859811e-81, 8.446936664813134e-81, 5.90349835695183e-81]
Mês 566: [5.404168003796933e-81, 6.043089597487849e-81, 4.223468332406567e-81]
Mês 567: [3.866238465225238e-81, 4.323334403037546e-81, 3.0215447987439245e-81]
Mês 568: [2.7659761612675583e-81, 3.09299

Mês 676: [5.423833448981277e-97, 6.065080040260904e-97, 4.238837281876753e-97]
Mês 677: [3.880307476505803e-97, 4.339066759185022e-97, 3.032540020130452e-97]
Mês 678: [2.776041383618601e-97, 3.104245981204642e-97, 2.169533379592511e-97]
Mês 679: [1.9860296665208232e-97, 2.220833106894881e-97, 1.552122990602321e-97]
Mês 680: [1.4208411515679047e-97, 1.5888237332166588e-97, 1.1104165534474406e-97]
Mês 681: [1.0164951772978175e-97, 1.1366729212543239e-97, 7.944118666083294e-98]
Mês 682: [7.272188339488278e-98, 8.131961418382541e-98, 5.6833646062716194e-98]
Mês 683: [5.202653630445594e-98, 5.817750671590623e-98, 4.0659807091912705e-98]
Mês 684: [3.722071477633566e-98, 4.162122904356476e-98, 2.9088753357953114e-98]
Mês 685: [2.6628365193373e-98, 2.977657182106853e-98, 2.081061452178238e-98]
Mês 686: [1.905040881489074e-98, 2.13026921546984e-98, 1.4888285910534265e-98]
Mês 687: [1.3629003259456054e-98, 1.5240327051912592e-98, 1.06513460773492e-98]
Mês 688: [9.750432741426137e-99, 1.090320260

Mês 789: [1.9932567100757248e-113, 2.2289145861709756e-113, 1.557771073631865e-113]
Mês 790: [1.426011507811861e-113, 1.59460536806058e-113, 1.1144572930854878e-113]
Mês 791: [1.0201941426473875e-113, 1.1408092062494888e-113, 7.9730268403029e-114]
Mês 792: [7.298651399308024e-114, 8.1615531411791e-114, 5.704046031247444e-114]
Mês 793: [5.221585776839039e-114, 5.8389211194464196e-114, 4.08077657058955e-114]
Mês 794: [3.73561587384112e-114, 4.177268621471232e-114, 2.9194605597232098e-114]
Mês 795: [2.6725264226802578e-114, 2.988492699072896e-114, 2.088634310735616e-114]
Mês 796: [1.911973211683571e-114, 2.1380211381442063e-114, 1.494246349536448e-114]
Mês 797: [1.3678598389793928e-114, 1.529578569346857e-114, 1.0690105690721032e-114]
Mês 798: [9.785913984878491e-115, 1.0942878711835142e-114, 7.647892846734285e-115]
Mês 799: [7.001017925264428e-115, 7.828731187902793e-115, 5.471439355917571e-115]
Mês 800: [5.008653465134911e-115, 5.600814340211542e-115, 3.9143655939513964e-115]
Mês 801: [

Mês 891: [2.915159851844127e-128, 3.25981208639631e-128, 2.2782573209264216e-128]
Mês 892: [2.0855575073834392e-128, 2.3321278814753016e-128, 1.629906043198155e-128]
Mês 893: [1.4920451493772818e-128, 1.6684460059067515e-128, 1.1660639407376508e-128]
Mês 894: [1.0674357911009059e-128, 1.1936361195018256e-128, 8.342230029533757e-129]
Mês 895: [7.636626603415879e-129, 8.539486328807248e-129, 5.968180597509128e-129]
Mês 896: [5.463379283905449e-129, 6.109301282732703e-129, 4.269743164403624e-129]
Mês 897: [3.9085992742470764e-129, 4.3707034271243594e-129, 3.0546506413663516e-129]
Mês 898: [2.79628184183545e-129, 3.126879419397661e-129, 2.1853517135621797e-129]
Mês 899: [2.0005100524112666e-129, 2.2370254734683603e-129, 1.5634397096988305e-129]
Mês 900: [1.4312006786739463e-129, 1.6004080419290133e-129, 1.1185127367341802e-129]
Mês 901: [1.0239065683113427e-129, 1.1449605429391571e-129, 8.002040209645067e-130]
Mês 902: [7.3252107566248e-130, 8.191252546490742e-130, 5.7248027146957854e-130]

Mês 997: [1.1168650362630417e-143, 1.2489092636825967e-143, 8.728529736519858e-144]
Mês 998: [7.990252265716955e-144, 8.934920290104334e-144, 6.244546318412984e-144]
Mês 999: [5.716369408734764e-144, 6.392201812573565e-144, 4.467460145052167e-144]
Mês 1000: [4.089592935297216e-144, 4.573095526987811e-144, 3.1961009062867823e-144]


3-element Vector{Float64}:
 4.089592935297216e-144
 4.573095526987811e-144
 3.1961009062867823e-144

In [8]:
p0 = [50; 25; 25; 0]
sistema_pop(1000, p0)

Mês 0: [50, 25, 25, 0]


LoadError: DimensionMismatch("second dimension of A, 3, does not match length of x, 4")

In [9]:
function pagerank(t, p0)
    p = zeros(4)
    T = [0 0 1 1/2; 1/3 0 0 0; 1/3 1/2 0 1/2; 1/3 1/2 0 0]
    
    println("Clique 0: ", p0)
    for i=1:t
        p = T*p0
        p0 = p
        # println("Mês ", i, ": ", p)
    end
    
    println("Clique ", t, ": ", p)
    return p
end

pagerank (generic function with 1 method)

In [10]:
p0 = [25; 25; 25; 25]
pagerank(100, p0)

Clique 0: [25, 25, 25, 25]
Clique 100: [38.709677419354776, 12.90322580645159, 29.032258064516082, 19.354838709677388]


4-element Vector{Float64}:
 38.709677419354776
 12.90322580645159
 29.032258064516082
 19.354838709677388

In [11]:
p0 = [0; 0; 0; 100]
pagerank(100, p0)

Clique 0: [0, 0, 0, 100]
Clique 100: [38.70967741935478, 12.903225806451594, 29.032258064516085, 19.35483870967739]


4-element Vector{Float64}:
 38.70967741935478
 12.903225806451594
 29.032258064516085
 19.35483870967739

In [12]:
function vampiros(t, p0)
    p = zeros(2)
    T = [1.01 0; 0.01 0.99]
    
    println("Ano 0: ", p0)
    for i=1:t
        p = T*p0
        p0 = p
        #println("Ano ", i, ": ", p)
    end
    
    println("Ano ", t, ": ", p)
    return p
end

vampiros (generic function with 1 method)

In [13]:
p0 = [100, 0]
vampiros(100, p0)

Ano 0: [100, 0]
Ano 100: [270.4813829421531, 116.93907440741496]


2-element Vector{Float64}:
 270.4813829421531
 116.93907440741496

In [19]:
A = [0 -1 0; 1 0 -1; 0 1 0]
b = [-38; -10; -10]
A

3×3 Matrix{Int64}:
 0  -1   0
 1   0  -1
 0   1   0